alps_error_init – ALPS
alps_error_init Subroutine
7 statements
public subroutine alps_error_init()
Uses
alps_var
Open a file for the error log.
Arguments
None
Calls
Called by
Contents
None
Call graph
alps_error_init calls get_runname, get_unused_unit
alps calls alps_error_init