alps_error – ALPS
alps_error Subroutine
53 statements
public subroutine alps_error(error_id)
Uses
alps_var
mpi
Error catching subroutine.
Arguments
Type Intent Optional Attributes Name
integer :: error_id
Index of error message.
Calls
Called by
Call graph
alps_error calls mpi_abort, output_time
get_indexed_double_namelist_unit calls alps_error
get_indexed_namelist_unit calls alps_error
init_param calls alps_error, get_indexed_double_namelist_unit, get_indexed_namelist_unit
integrate_resu_rel calls alps_error
lm_nonlinear_fit calls alps_error
om_double_scan calls alps_error, disp, calc_eigen, secant, secant_osc
om_scan calls alps_error, disp, calc_eigen, secant, secant_osc
output_fit calls alps_error
set_polynomial_basis calls alps_error
alps calls alps_error, init_param, om_double_scan, om_scan, determine_param_fit, map_search, refine_guess
determine_param_fit calls lm_nonlinear_fit, output_fit, set_polynomial_basis
integrate_res_rel calls integrate_resu_rel
full_integrate calls integrate_res_rel
disp calls full_integrate
calc_eigen calls disp
map_search calls disp, refine_guess
refine_guess calls disp, secant, secant_osc
secant calls disp
secant_osc calls disp