BESSJ – ALPS
BESSJ Function
54 statements
public function BESSJ(N, X)
Arguments
Type Intent Optional Attributes Name
integer :: N
real(kind=8) :: X
Return Value doubleprecision
Calls
Called by
Contents
Call graph
bessj calls float, bessj0, bessj1
determine_bessel_array calls bessj
determine_nmax calls bessj
int_t_rel calls bessj
funct_g_rel calls int_t_rel
integrate_resu_rel calls int_t_rel, principal_integral_rel
om_double_scan calls determine_bessel_array, determine_nmax, disp, secant
om_scan calls determine_bessel_array, determine_nmax, disp, calc_eigen, secant
alps calls determine_bessel_array, determine_nmax, om_double_scan, om_scan, map_search, refine_guess
integrate_res_rel calls integrate_resu_rel
principal_integral_rel calls funct_g_rel
full_integrate calls integrate_res_rel
disp calls full_integrate
calc_eigen calls disp
map_search calls disp, refine_guess
refine_guess calls disp, secant
secant calls disp