BESSJ1 – ALPS
BESSJ1 Function
25 statements
public function BESSJ1(X)
This subroutine calculates the First Kind Bessel Function of order 1, for any real number X. The polynomial approximation by series of Chebyshev polynomials is used for 0<X<8 and 0<8/X<1. References: M.Abramowitz, I.A.Stegun, Handbook of Mathematical Functions, 1965. C.W.Clenshaw, Chebyshev Series for Mathematical Functions, Mathematical Tables, Vol. 5, 1962.
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: X
Argument of the Bessel function.
Return Value doubleprecision
Called by
Call graph
bessj calls bessj1
determine_bessel_array calls bessj
determine_nmax calls bessj
int_t_rel calls bessj
funct_g_rel calls int_t_rel
integrate_resu_rel calls int_t_rel, principal_integral_rel
om_double_scan calls determine_bessel_array, determine_nmax, disp, calc_eigen, secant, secant_osc
om_scan calls determine_bessel_array, determine_nmax, disp, calc_eigen, secant, secant_osc
alps calls determine_bessel_array, determine_nmax, om_double_scan, om_scan, map_search, refine_guess
integrate_res_rel calls integrate_resu_rel
principal_integral_rel calls funct_g_rel
full_integrate calls integrate_res_rel
disp calls full_integrate
calc_eigen calls disp
map_search calls disp, refine_guess
refine_guess calls disp, secant, secant_osc
secant calls disp
secant_osc calls disp