BESSI0 – ALPS
BESSI0 Function
16 statements
private function BESSI0(X)
Auxiliary Bessel functions for N=0, N=1
Arguments
Type Intent Optional Attributes Name
real(kind=8) :: X
Return Value doubleprecision
Called by
Contents
Call graph
bessi calls bessi0
besseli calls bessi
calc_chi calls besseli, calc_ypsilon
calc_ypsilon calls besseli
disp calls calc_chi
calc_eigen calls disp
map_search calls disp, refine_guess
om_double_scan calls disp, secant
om_scan calls disp, calc_eigen, secant
refine_guess calls disp, secant
secant calls disp
alps calls map_search, om_double_scan, om_scan, refine_guess