besselI – ALPS
besselI Function
10 statements
private function besselI(n, x)
Calculates the modified Bessel function of argument x and order n.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: n
Order of the modified Bessel function.
double precision, intent(in) :: x
Argument of the modified Bessel function.
Return Value doubleprecision
Calls
Called by
Call graph
besseli calls bessi
bessi calls dfloat, float, bessi0, bessi1
calc_chi calls besseli, calc_ypsilon
calc_ypsilon calls besseli
disp calls calc_chi
calc_eigen calls disp
map_search calls disp, refine_guess
om_double_scan calls disp, calc_eigen, secant, secant_osc
om_scan calls disp, calc_eigen, secant, secant_osc
refine_guess calls disp, secant, secant_osc
secant calls disp
secant_osc calls disp
alps calls map_search, om_double_scan, om_scan, refine_guess