calc_ypsilon – ALPS
calc_ypsilon Subroutine
53 statements
private subroutine calc_ypsilon(Y, j, n, kz, kperp, x)
Uses
alps_var
Calculates the Y-tensor according to Stix for a bi-Maxwelling, using the NHDS calculation.
Arguments
Type Intent Optional Attributes Name
double complex, intent(out) :: Y(3,3)
Y-tensor as defined by Stix.
integer, intent(in) :: j
Index for species.
integer, intent(in) :: n
Index of sum over Bessel functions.
double precision, intent(in) :: kz
Normalised parallel wavenumber.
double precision, intent(in) :: kperp
Normalised perpendicular wavenumber.
double complex, intent(in) :: x
Normalised complex frequency.
Calls
Called by
Call graph
calc_ypsilon calls besseli, dispfunct
besseli calls bessi
dispfunct calls wofz
bessi calls dfloat, float, bessi0, bessi1
wofz calls dcos, dexp, dsin, idint, idnint
calc_chi calls calc_ypsilon
disp calls calc_chi
calc_eigen calls disp
map_search calls disp, refine_guess
om_double_scan calls disp, calc_eigen, secant
om_scan calls disp, calc_eigen, secant
refine_guess calls disp, secant
secant calls disp
alps calls map_search, om_double_scan, om_scan, refine_guess