calc_chi – ALPS
calc_chi Subroutine
67 statements
public subroutine calc_chi(chi, j, kz, kperp, x)
Uses
alps_var
Subroutine that calculates the susceptibility of species j based on NHDS.
Arguments
Type Intent Optional Attributes Name
double complex, intent(out) :: chi(3,3)
Susceptibility tensor of species j.
integer, intent(in) :: j
Index for species.
double precision, intent(in) :: kz
Normalised parallel wavenumber.
double precision, intent(in) :: kperp
Normalised perpendicular wavenumber.
double complex, intent(in) :: x
Normalised complex frequency.
Calls
Called by
Call graph
calc_chi calls besseli, calc_chi_cold, calc_ypsilon
besseli calls bessi
calc_ypsilon calls besseli, dispfunct
bessi calls dfloat, float, bessi0, bessi1
dispfunct calls wofz
wofz calls dcos, dexp, dsin, idint, idnint
disp calls calc_chi
calc_eigen calls disp
map_search calls disp, refine_guess
om_double_scan calls disp, calc_eigen, secant, secant_osc
om_scan calls disp, calc_eigen, secant, secant_osc
refine_guess calls disp, secant, secant_osc
secant calls disp
secant_osc calls disp
alps calls map_search, om_double_scan, om_scan, refine_guess