calc_eigen – ALPS
calc_eigen Subroutine
139 statements
public subroutine calc_eigen(omega, electric, magnetic, vmean, ds, Ps, Ps_split, eigen_L, heat_L)
Uses
alps_var
This subroutine calculates the relative electric and magnetic field amplitudes, the relative fluctuations in the density and velocity of all species, and the heating rates of the given solution. It is based on the calc_eigen routine by Greg Howes and Kris Klein, found in PLUME. The splitting by mechanisms is described in Huang, Howes, and Brown, JPP 2024.
Arguments
Type Intent Optional Attributes Name
double complex, intent(in) :: omega
Complex wave frequency .
double complex, intent(out), dimension(1:3) :: electric
Relative electric field amplitude (eigenfunction).
double complex, intent(out), dimension(1:3) :: magnetic
Relative magnetic field amplitude (eigenfunction).
double complex, intent(out), dimension(1:3,1:nspec) :: vmean
Relative velocity-fluctuation amplitude (eigenfunction).
double complex, intent(out), dimension(1:nspec) :: ds
Relative density-fluctuation amplitude (eigenfunction).
double precision, intent(out), dimension(1:nspec) :: Ps
Relative heating rate of a given species.
double precision, dimension(1:6,1:nspec) :: Ps_split
Relative heating rate of a given species split by component
logical, intent(in) :: eigen_L
Check whether eigenfunction calculation is requested.
logical, intent(in) :: heat_L
Check whether eigenfunction calculation is requested.
Calls
Called by
Call graph
calc_eigen calls disp
disp calls mpi_barrier, mpi_bcast, mpi_reduce, calc_chi, determine_resonances, full_integrate, int_ee, int_ee_rel
calc_chi calls besseli, calc_chi_cold, calc_ypsilon
full_integrate calls integrate, integrate_res, integrate_res_rel, landau_integrate, landau_integrate_rel
int_ee_rel calls determine_sproc_rel
besseli calls bessi
calc_ypsilon calls besseli, dispfunct
integrate calls int_t, resu
integrate_res calls integrate, funct_g
integrate_res_rel calls determine_sproc_rel, integrate_resu_rel
landau_integrate calls eval_fit, int_t_res
landau_integrate_rel calls determine_sproc_rel, eval_fit, int_t_res_rel
bessi calls dfloat, float, bessi0, bessi1
dispfunct calls wofz
eval_fit calls distribution_analyt, fit_function, fit_function_poly
funct_g calls int_t
int_t_res_rel calls cbessj
integrate_resu_rel calls alps_error, int_t_rel, principal_integral_rel, resu_rel
alps_error calls mpi_abort, output_time
cbessj calls fact
int_t_rel calls bessj
principal_integral_rel calls funct_g_rel
wofz calls dcos, dexp, dsin, idint, idnint
bessj calls float, bessj0, bessj1
funct_g_rel calls int_t_rel
om_double_scan calls calc_eigen
om_scan calls calc_eigen
alps calls om_double_scan, om_scan