CBESSJ – ALPS
CBESSJ Subroutine
22 statements
public subroutine CBESSJ(z, nu, z1)
This subroutine calculates the complex Bessel function. It is based on the CBESSJ function release 1.1 by J-P Moreau, Paris (www.jpmoreau.fr).
Arguments
Type Intent Optional Attributes Name
double complex, intent(in) :: z
Argument of the Bessel function.
integer, intent(in) :: nu
Order of Bessel function.
double complex, intent(out) :: z1
Resulting value of Bessel function.
Calls
Called by
Contents
Call graph
cbessj calls fact
int_t_res_rel calls cbessj
landau_integrate_rel calls int_t_res_rel
full_integrate calls landau_integrate_rel
disp calls full_integrate
calc_eigen calls disp
map_search calls disp, refine_guess
om_double_scan calls disp, calc_eigen, secant
om_scan calls disp, calc_eigen, secant
refine_guess calls disp, secant
secant calls disp
alps calls map_search, om_double_scan, om_scan, refine_guess