derivative_f0_rel – ALPS
derivative_f0_rel Subroutine
140 statements
public subroutine derivative_f0_rel(is, is_rel)
Uses
alps_var
alps_io
This subroutine calculates the derivatives of the background velocity distribution function f0 for the relativistic calculation.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: is
Index of particle species.
integer, intent(in) :: is_rel
Index for relativistic species (if any).
Calls
Called by
Call graph
derivative_f0_rel calls get_unused_unit, polyharmonic_spline
polyharmonic_spline calls dgesv
derivative_f0 calls derivative_f0_rel
alps calls derivative_f0