derivative_f0 – ALPS
derivative_f0 Subroutine
123 statements
public subroutine derivative_f0()
Uses
alps_var
alps_io
alps_fns_rel
This subroutine calculates the perpendicular and parallel derivatives of the background velocity distribution function f0.
Arguments
None
Calls
Called by
Contents
None
Call graph
derivative_f0 calls derivative_f0_rel, get_unused_unit
derivative_f0_rel calls get_unused_unit, polyharmonic_spline
polyharmonic_spline calls dgesv
alps calls derivative_f0