determine_nmax – ALPS
determine_nmax Subroutine
65 statements
public subroutine determine_nmax()
Uses
mpi
alps_var
alps_fns_rel
This subroutine determines the maximum required order of the Bessel functions in Eq. (2.9) of the code paper.
Arguments
None
Calls
Called by
Contents
None
Call graph
determine_nmax calls mpi_barrier, bessj
bessj calls float, bessj0, bessj1
om_double_scan calls determine_nmax
om_scan calls determine_nmax
alps calls determine_nmax, om_double_scan, om_scan