determine_sproc_rel – ALPS
determine_sproc_rel Subroutine
14 statements
private subroutine determine_sproc_rel(sproc_rel)
Uses
alps_var
This subroutine determines sproc_rel for the given process.
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: sproc_rel
is_rel of the current process.
Called by
Contents
Call graph
int_ee_rel calls determine_sproc_rel
integrate_res_rel calls determine_sproc_rel
landau_integrate_rel calls determine_sproc_rel
disp calls int_ee_rel, full_integrate
full_integrate calls integrate_res_rel, landau_integrate_rel
calc_eigen calls disp
map_search calls disp, refine_guess
om_double_scan calls disp, calc_eigen, secant
om_scan calls disp, calc_eigen, secant
refine_guess calls disp, secant
secant calls disp
alps calls map_search, om_double_scan, om_scan, refine_guess