determine_JT – ALPS
determine_JT Subroutine
103 statements
private subroutine determine_JT(is, n_params, nJT, JT, params, iperp, upper_limit, ipparbar_lower)
Uses
alps_var
This subroutine calculates the transposed Jacobian matrix of the fit function with respect to the fit parameter array.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: is
Index of species for which determine_JT is executed.
integer, intent(in) :: n_params
Total number of fit parameters for a given species.
integer, intent(in) :: nJT
First dimension of matrix JT.
double precision, intent(out) :: JT(nJT,0:upper_limit)
Transposed Jacobian matrix of the fit function.
double precision, intent(in) :: params(n_params)
Array of fit parameters.
integer, intent(in) :: iperp
Index of perpendicular momentum at which JT is evaluated.
integer, intent(in) :: upper_limit
Upper limit of iperp space (relativistic and non-relativistic).
integer, intent(in) :: ipparbar_lower
Lower index of parallel momentum (relativistic).
Called by
Contents
Call graph
lm_nonlinear_fit calls determine_jt
determine_param_fit calls lm_nonlinear_fit
alps calls determine_param_fit