determine_param_fit – ALPS
determine_param_fit Subroutine
234 statements
public subroutine determine_param_fit()
Uses
alps_var
This is the fitting routine for the hybrid analytic continuation. It determines the full field param_fit.
Arguments
None
Calls
Called by
Call graph
determine_param_fit calls determine_glls, lm_nonlinear_fit, output_fit, set_polynomial_basis
determine_glls calls least_squares_fit
lm_nonlinear_fit calls dgetrf, dgetri, alps_error, determine_jt, fit_function
output_fit calls alps_error, eval_fit, isnancheck
set_polynomial_basis calls alps_error
alps_error calls mpi_abort, output_time
eval_fit calls fit_function, distribution_analyt, fit_function_poly
least_squares_fit calls dgemm, dgemv, dgesv
alps calls determine_param_fit