determine_GLLS – ALPS
determine_GLLS Subroutine
42 statements
private subroutine determine_GLLS(is)
Uses
alps_var
This subroutine evaluates the General Linear Least Squares fit to the distribution function for component 'is' using the selected polynomial basis functions.
Arguments
Type Intent Optional Attributes Name
integer :: is
Index of species.
Calls
Called by
Call graph
determine_glls calls least_squares_fit
least_squares_fit calls dgemm, dgemv, dgesv
determine_param_fit calls determine_glls
alps calls determine_param_fit