determine_bessel_array – ALPS
determine_bessel_array Subroutine
21 statements
public subroutine determine_bessel_array()
Uses
alps_fns_rel
alps_io
alps_var
This subroutine determines the array of Bessel functions that is used in the T-tensor of Eq. (2.10) of the code paper.
Arguments
None
Calls
Called by
Call graph
determine_bessel_array calls bessj
bessj calls float, bessj0, bessj1
om_double_scan calls determine_bessel_array
om_scan calls determine_bessel_array
alps calls determine_bessel_array, om_double_scan, om_scan