determine_resonances – ALPS
determine_resonances Subroutine
48 statements
public subroutine determine_resonances(om, nn, found_res_plus, found_res_minus)
Uses
alps_var
alps_io
This subroutine determines whether any kinetic resonances are located in the integration domain.
Arguments
Type Intent Optional Attributes Name
double complex, intent(in) :: om
Complex wave frequency .
integer, intent(in) :: nn
Order of Bessel function.
logical, intent(out) :: found_res_plus
Check whether a resonance is found at positive n.
logical, intent(out) :: found_res_minus
Check whether a resonance is found at negative n.
Called by
Call graph
disp calls determine_resonances
calc_eigen calls disp
map_search calls disp, refine_guess
om_double_scan calls disp, calc_eigen, secant
om_scan calls disp, calc_eigen, secant
refine_guess calls disp, secant
secant calls disp
alps calls map_search, om_double_scan, om_scan, refine_guess