dispfunct – ALPS
dispfunct Function
21 statements
private function dispfunct(zeta, kpos)
Calculates the dispersion function based on the complex error function.
Arguments
Type Intent Optional Attributes Name
double complex, intent(in) :: zeta
Argument of dispersion function.
logical, intent(in) :: kpos
Check whether kpar is positive.
Return Value doublecomplex
Calls
Called by
Contents
Call graph
dispfunct calls wofz
wofz calls dcos, dexp, dsin, idint, idnint
calc_ypsilon calls dispfunct
calc_chi calls calc_ypsilon
disp calls calc_chi
calc_eigen calls disp
map_search calls disp, refine_guess
om_double_scan calls disp, calc_eigen, secant
om_scan calls disp, calc_eigen, secant
refine_guess calls disp, secant
secant calls disp
alps calls map_search, om_double_scan, om_scan, refine_guess