disp – ALPS
disp Function
177 statements
public function disp(om)
Uses
mpi
alps_fns_rel
alps_nhds
alps_var
This function returns the determinant of the dispersion tensor for a given frequency om.
Arguments
Type Intent Optional Attributes Name
double complex, intent(in) :: om
Complex wave frequency .
Return Value doublecomplex
Calls
Called by
Call graph
disp calls mpi_barrier, mpi_bcast, mpi_reduce, calc_chi, determine_resonances, full_integrate, int_ee, int_ee_rel
calc_chi calls besseli, calc_chi_cold, calc_ypsilon
full_integrate calls integrate, integrate_res, integrate_res_rel, landau_integrate, landau_integrate_rel
int_ee_rel calls determine_sproc_rel
besseli calls bessi
calc_ypsilon calls besseli, dispfunct
integrate calls int_t, resu
integrate_res calls integrate, funct_g
integrate_res_rel calls determine_sproc_rel, integrate_resu_rel
landau_integrate calls eval_fit, int_t_res
landau_integrate_rel calls determine_sproc_rel, eval_fit, int_t_res_rel
bessi calls dfloat, float, bessi0, bessi1
dispfunct calls wofz
eval_fit calls distribution_analyt, fit_function, fit_function_poly
funct_g calls int_t
int_t_res_rel calls cbessj
integrate_resu_rel calls alps_error, int_t_rel, principal_integral_rel, resu_rel
alps_error calls mpi_abort, output_time
cbessj calls fact
int_t_rel calls bessj
principal_integral_rel calls funct_g_rel
wofz calls dcos, dexp, dsin, idint, idnint
bessj calls float, bessj0, bessj1
funct_g_rel calls int_t_rel
calc_eigen calls disp
map_search calls disp, refine_guess
om_double_scan calls disp, calc_eigen, secant, secant_osc
om_scan calls disp, calc_eigen, secant, secant_osc
refine_guess calls disp, secant, secant_osc
secant calls disp
secant_osc calls disp
alps calls map_search, om_double_scan, om_scan, refine_guess