distribution_analyt – ALPS
distribution_analyt Function
22 statements
public function distribution_analyt(is, pperp, ppar)
This function returns the pre-defined function as f0.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: is
Index of species.
double precision :: pperp
Perpendicular momentum.
double complex :: ppar
Parallel momentum.
Return Value doublecomplex
Called by
Call graph
eval_fit calls distribution_analyt
generate_distribution calls distribution_analyt
landau_integrate calls eval_fit
landau_integrate_rel calls eval_fit
output_fit calls eval_fit
determine_param_fit calls output_fit
full_integrate calls landau_integrate, landau_integrate_rel
disp calls full_integrate
alps calls determine_param_fit, map_search, om_double_scan, om_scan, refine_guess
calc_eigen calls disp
map_search calls disp, refine_guess
om_double_scan calls disp, calc_eigen, secant, secant_osc
om_scan calls disp, calc_eigen, secant, secant_osc
refine_guess calls disp, secant, secant_osc
secant calls disp
secant_osc calls disp