eval_fit – ALPS
eval_fit Function
98 statements
public function eval_fit(is, iperp, ppar_valC)
Uses
alps_var
alps_distribution_analyt
This function evaluates the fit to f0 at and the complex parallel momentum ppar_valC. It requires the fit parameters that will be determined by the subroutine determine_param_fit.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: is
Index of species for which eval_fit is executed.
integer, intent(in) :: iperp
Index of perpendicular momentum at which eval_fit is executed.
double complex, intent(in) :: ppar_valC
Complex parallel momentum at which eval_fit is executed.
Return Value doublecomplex
Calls
Called by
Call graph
eval_fit calls distribution_analyt, fit_function, fit_function_poly
landau_integrate calls eval_fit
landau_integrate_rel calls eval_fit
output_fit calls eval_fit
determine_param_fit calls output_fit
full_integrate calls landau_integrate, landau_integrate_rel
disp calls full_integrate
alps calls determine_param_fit, map_search, om_double_scan, om_scan, refine_guess
calc_eigen calls disp
map_search calls disp, refine_guess
om_double_scan calls disp, calc_eigen, secant, secant_osc
om_scan calls disp, calc_eigen, secant, secant_osc
refine_guess calls disp, secant, secant_osc
secant calls disp
secant_osc calls disp