Fact – ALPS
Fact Function
12 statements
private function Fact(k)
This function returns the factorial k! of its argument k.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: k
Argument of the factorial.
Return Value doubleprecision
Called by
Call graph
cbessj calls fact
int_t_res_rel calls cbessj
landau_integrate_rel calls int_t_res_rel
full_integrate calls landau_integrate_rel
disp calls full_integrate
calc_eigen calls disp
map_search calls disp, refine_guess
om_double_scan calls disp, calc_eigen, secant
om_scan calls disp, calc_eigen, secant
refine_guess calls disp, secant
secant calls disp
alps calls map_search, om_double_scan, om_scan, refine_guess