fit_function_poly – ALPS
fit_function_poly Function
43 statements
public function fit_function_poly(is, iperp, ppar_val, n_poly, fit_coeffs)
Uses
alps_var
This function evaluates the orthogonal polynomical fit to f0 at real pperp_val and complex ppar_val, with the one-dimensional polynomical coefficient array fit_coeffs is fed into the function. For the evaluation in ALPS, use eval_fit. kgk: should this be .gt. or .ge. ?
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: is
Index of species for which eval_fit is executed.
integer, intent(in) :: iperp
Index of perpendicular momentum at which fit_function_poly is executed.
double complex :: ppar_val
Complex parallel momentum.
integer :: n_poly
Maximum Polynomial Order
double precision, intent(in) :: fit_coeffs(0:n_poly)
Array of polynomial coefficients
Return Value doublecomplex
Called by
Call graph
eval_fit calls fit_function_poly
landau_integrate calls eval_fit
landau_integrate_rel calls eval_fit
output_fit calls eval_fit
determine_param_fit calls output_fit
full_integrate calls landau_integrate, landau_integrate_rel
disp calls full_integrate
alps calls determine_param_fit, map_search, om_double_scan, om_scan, refine_guess
calc_eigen calls disp
map_search calls disp, refine_guess
om_double_scan calls disp, calc_eigen, secant, secant_osc
om_scan calls disp, calc_eigen, secant, secant_osc
refine_guess calls disp, secant, secant_osc
secant calls disp
secant_osc calls disp