fit_function – ALPS
fit_function Function
44 statements
private function fit_function(is, n_params, params, pperp_val, ppar_val)
Uses
alps_var
This function evaluates the fit to f0 at real pperp_val and complex ppar_val, provided that the one-dimensional fit-parameter array params is fed into the function. This is only used during the fitting. For the evaluation in ALPS, use eval_fit.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: is
Index of species for which eval_fit is executed.
integer, intent(in) :: n_params
Total number of fit parameters for a given species.
double precision, intent(in) :: params(n_params)
Array of fit parameters.
double precision, intent(in) :: pperp_val
Perpendicular momentum.
double complex, intent(in) :: ppar_val
Complex parallel momentum.
Return Value doublecomplex
Called by
Call graph
eval_fit calls fit_function
lm_nonlinear_fit calls fit_function
determine_param_fit calls lm_nonlinear_fit, output_fit
landau_integrate calls eval_fit
landau_integrate_rel calls eval_fit
output_fit calls eval_fit
full_integrate calls landau_integrate, landau_integrate_rel
alps calls determine_param_fit, map_search, om_double_scan, om_scan, refine_guess
disp calls full_integrate
calc_eigen calls disp
map_search calls disp, refine_guess
om_double_scan calls disp, calc_eigen, secant, secant_osc
om_scan calls disp, calc_eigen, secant, secant_osc
refine_guess calls disp, secant, secant_osc
secant calls disp
secant_osc calls disp