full_integrate – ALPS
full_integrate Function
28 statements
public function full_integrate(om, nn, mode, found_res)
Uses
alps_var
alps_fns_rel
This function returns the full integral expression according to Eq. (2.9) in the code paper.
Arguments
Type Intent Optional Attributes Name
double complex, intent(in) :: om
Complex wave frequency .
integer, intent(in) :: nn
Order of the Bessel function.
integer, intent(in) :: mode
Index of the entries in the T-tensor of Eq. (2.10).
logical, intent(in) :: found_res
Check whether a resonance is found.
Return Value doublecomplex
Calls
Called by
Call graph
full_integrate calls integrate, integrate_res, integrate_res_rel, landau_integrate, landau_integrate_rel
integrate calls int_t, resu
integrate_res calls integrate, funct_g
integrate_res_rel calls determine_sproc_rel, integrate_resu_rel
landau_integrate calls eval_fit, int_t_res
landau_integrate_rel calls determine_sproc_rel, eval_fit, int_t_res_rel
eval_fit calls distribution_analyt, fit_function, fit_function_poly
funct_g calls int_t
int_t_res_rel calls cbessj
integrate_resu_rel calls alps_error, int_t_rel, principal_integral_rel, resu_rel
alps_error calls mpi_abort, output_time
cbessj calls fact
int_t_rel calls bessj
principal_integral_rel calls funct_g_rel
bessj calls float, bessj0, bessj1
funct_g_rel calls int_t_rel
disp calls full_integrate
calc_eigen calls disp
map_search calls disp, refine_guess
om_double_scan calls disp, calc_eigen, secant, secant_osc
om_scan calls disp, calc_eigen, secant, secant_osc
refine_guess calls disp, secant, secant_osc
secant calls disp
secant_osc calls disp
alps calls map_search, om_double_scan, om_scan, refine_guess