funct_g_rel – ALPS
funct_g_rel Function
33 statements
private function funct_g_rel(sproc_rel, pparbar, igamma, om, nn, mode)
Uses
alps_var
This function returns the function from Eq. (3.2) of the code paper for a relativistic calculation.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: sproc_rel
is_rel of the current process.
double precision, intent(in) :: pparbar
Relativistic parallel momentum.
integer, intent(in) :: igamma
Index of .
double complex, intent(in) :: om
Complex wave frequency .
integer, intent(in) :: nn
Order of the Bessel function.
integer, intent(in) :: mode
Index of the entries in the T-tensor of Eq. (2.10).
Return Value doublecomplex
Calls
Called by
Contents
Call graph
funct_g_rel calls int_t_rel
int_t_rel calls bessj
bessj calls float, bessj0, bessj1
principal_integral_rel calls funct_g_rel
integrate_resu_rel calls principal_integral_rel
integrate_res_rel calls integrate_resu_rel
full_integrate calls integrate_res_rel
disp calls full_integrate
calc_eigen calls disp
map_search calls disp, refine_guess
om_double_scan calls disp, calc_eigen, secant
om_scan calls disp, calc_eigen, secant
refine_guess calls disp, secant
secant calls disp
alps calls map_search, om_double_scan, om_scan, refine_guess