funct_g – ALPS
funct_g Function
29 statements
public function funct_g(ppar_real, iperp, om, nn, mode)
Uses
alps_var
This function returns the function from Eq. (3.2) of the code paper.
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: ppar_real
Real part of the momentum at which is evaluated.
integer, intent(in) :: iperp
Index of the perpendicular momentum.
double complex, intent(in) :: om
Complex wave frequency .
integer, intent(in) :: nn
Order of the Bessel function.
integer, intent(in) :: mode
Index of the entries in the T-tensor of Eq. (2.10).
Return Value doublecomplex
Calls
Called by
Contents
Call graph
funct_g calls int_t
integrate_res calls funct_g
full_integrate calls integrate_res
disp calls full_integrate
calc_eigen calls disp
map_search calls disp, refine_guess
om_double_scan calls disp, calc_eigen, secant
om_scan calls disp, calc_eigen, secant
refine_guess calls disp, secant
secant calls disp
alps calls map_search, om_double_scan, om_scan, refine_guess