get_indexed_double_namelist_unit – ALPS
get_indexed_double_namelist_unit Subroutine
37 statements
public subroutine get_indexed_double_namelist_unit(unit, nml, spec_in, index_in)
Uses
alps_var
A version of get_indexed_namelist_unit, extended to allow for double indexing in order to read in multiple fits for a single species.
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: unit
Unit to be defined.
character(len=*), intent(in) :: nml
Character string for namelist to be read in.
integer, intent(in) :: spec_in
First index of namelist to be read in.
integer, intent(in) :: index_in
Second index of namelist to be read in.
Calls
Called by
Contents
Call graph
get_indexed_double_namelist_unit calls alps_error, get_unused_unit, input_unit, input_unit_exist
alps_error calls mpi_abort, output_time
init_param calls get_indexed_double_namelist_unit
alps calls init_param