get_indexed_namelist_unit – ALPS
get_indexed_namelist_unit Subroutine
35 statements
private subroutine get_indexed_namelist_unit(unit, nml, index_in)
Uses
alps_var
Determines unused I/O unit.
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: unit
Unit to be defined.
character(len=*), intent(in) :: nml
Character string for namelist to be read in.
integer, intent(in) :: index_in
Index of namelist to be read in.
Calls
Called by
Contents
Call graph
get_indexed_namelist_unit calls alps_error, get_unused_unit, input_unit, input_unit_exist
alps_error calls mpi_abort, output_time
init_param calls get_indexed_namelist_unit
alps calls init_param