get_unused_unit – ALPS
get_unused_unit Subroutine
11 statements
public subroutine get_unused_unit(unit)
Determine unused number for I/O index.
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: unit
Unit to be assigned.
Called by
Contents
Call graph
alps_error_init calls get_unused_unit
derivative_f0 calls get_unused_unit, derivative_f0_rel
derivative_f0_rel calls get_unused_unit
get_indexed_double_namelist_unit calls get_unused_unit
get_indexed_namelist_unit calls get_unused_unit
init_param calls get_unused_unit, get_indexed_double_namelist_unit, get_indexed_namelist_unit
map_search calls get_unused_unit, refine_guess
om_double_scan calls get_unused_unit
om_scan calls get_unused_unit
read_f0 calls get_unused_unit
refine_guess calls get_unused_unit
alps calls alps_error_init, derivative_f0, init_param, map_search, om_double_scan, om_scan, read_f0, refine_guess