init_param – ALPS
init_param Subroutine
171 statements
public subroutine init_param()
Uses
alps_var
Read in system parameters from *.in file. Only processor 0 calls this routine:
Arguments
None
Calls
Called by
Namelists
Namelist system
Variables
Name Type Default Description
kperp double precision None
Perpendicular wavenumber, normalized by inverse reference inertial length, .
kpar double precision None
Parallel wavenumber, normalized by inverse reference inertial length, .
nspec integer None
Number of plasma components.
nroots integer None
Number of dispersion solutions under consideration.
use_map logical None
Choice of: (T) searching for roots over a map in complex frequency space, via map_read; (F) input (nroots) guesses for solutions, via solution_read
writeOut logical .true.
Write or suppress output to screen.
nperp integer None
Number of perpendicular momentum space grid points, .
npar integer None
Number of parallel momentum space grid points, .
ngamma integer 100
Number of grid points in relativitic , (Eqn. 3.14).
npparbar integer 200
Number of grid points in dimensionless paralell momentum , .
vA double precision None
Alfven Velocity, normalized to speed of light, .
arrayName character(len=75) None
Name of input files for distributions.
Bessel_zero double precision 1.d-45
Calculate Bessel functions until the maximum is less than this value.
secant_method integer 2
Selection of root finding method. 0: secant 1: rtsec 2: secant_osc: an improvement to reduce oscillatory loops.
numiter integer 50
Maximum number of iterations in secant method.
kperp_norm logical .true.
Use the tensor in Stix's (10-57) (true) or Multiply by kperp^2 d_ref^2 (false)
D_threshold double precision 1.d-5
Minimum threshold for secant method.
D_prec double precision 1.d-5
Size of bounding region for secant method.
D_gap double precision 1.d-5
Size of allowable difference between roots.
positions_principal integer 5
Number of parallel momentum steps distant from the resonant momentum included in the numerical calculation of Eqn 3.5, .
Tlim double precision 0.01d0
Threshold for analytical principal-value integration for evaluating Eqn 3.6 and 3.7, .
maxsteps_fit integer 500
Maximum number of fitting iterations.
lambda_initial_fit double precision 1.d0
Inital Levenberg-Marquardt damping parameter.
lambdafac_fit double precision 1.d1
Adjustment factor for Levenberg-Marquardt damping parameter.
epsilon_fit double precision 1.d-8
Convergence for Levenberg-Marquardt fit.
fit_check logical .true.
If true, output fitted functions to ASCII file for each species.
determine_minima logical .true.
If true, after map search, determine minima and refine solutions.
n_resonance_interval integer 100
How many steps should be used to integrate around the resonance, , used for integrating near poles (see section 3.1).
scan_option integer 1
Select case for scans; 1) consecutive scans along input paths in wavevector space, 2) double scans of two selected parameters.
n_scan integer 0
Number of wavevector scans. Must be set to 2 for scan_option=2; Must be 1 or larger for scan_option=1. 0 turns off wavevector scans.
Call graph
init_param calls alps_error, bm_read, fit_read, get_indexed_double_namelist_unit, get_indexed_namelist_unit, get_unused_unit, map_read, poly_read, scan_read, solution_read, spec_read
alps_error calls mpi_abort, output_time
get_indexed_double_namelist_unit calls alps_error, get_unused_unit, input_unit, input_unit_exist
get_indexed_namelist_unit calls alps_error, get_unused_unit, input_unit, input_unit_exist
alps calls init_param