input_unit – ALPS
input_unit Function
24 statements
private function input_unit(nml)
Assigns input unit for namelist opening.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: nml
Namelist string.
Return Value integer
I/O dummy indices.
Called by
Contents
Call graph
get_indexed_double_namelist_unit calls input_unit
get_indexed_namelist_unit calls input_unit
init_param calls get_indexed_double_namelist_unit, get_indexed_namelist_unit
alps calls init_param