input_unit_exist – ALPS
input_unit_exist Function
26 statements
function input_unit_exist(nml, exist)
Determine if a particular namelist already opened.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: nml
Namelist to be opened.
logical, intent(out) :: exist
Determination if namelist is open.
Return Value integer
I/O dummy index.
Called by
Contents
Call graph
get_indexed_namelist_unit calls input_unit_exist
read_in_params calls get_indexed_namelist_unit
generate_distribution calls read_in_params