input_unit_exist – ALPS
input_unit_exist Function
25 statements
private function input_unit_exist(nml, exist)
Determine if a particular namelist already opened.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: nml
Namelist to be opened.
logical, intent(out) :: exist
Determination if namelist is open.
Return Value integer
I/O dummy indices.
Called by
Contents
Call graph
get_indexed_double_namelist_unit calls input_unit_exist
get_indexed_namelist_unit calls input_unit_exist
init_param calls get_indexed_double_namelist_unit, get_indexed_namelist_unit
alps calls init_param