int_T – ALPS
int_T Function
67 statements
private function int_T(nn, iperp, ipar, mode)
Uses
alps_var
This function returns the T-tensor according to Eq. (2.10) of the code paper.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: nn
Order of the Bessel function.
integer, intent(in) :: iperp
Index to loop over perpendicular momentum.
integer, intent(in) :: ipar
Index to loop over parallel momentum.
integer, intent(in) :: mode
Index of the entries in the T-tensor of Eq. (2.10).
Return Value doublecomplex
Called by
Call graph
funct_g calls int_t
integrate calls int_t
full_integrate calls integrate, integrate_res
integrate_res calls funct_g, integrate
disp calls full_integrate
calc_eigen calls disp
map_search calls disp, refine_guess
om_double_scan calls disp, calc_eigen, secant, secant_osc
om_scan calls disp, calc_eigen, secant, secant_osc
refine_guess calls disp, secant, secant_osc
secant calls disp
secant_osc calls disp
alps calls map_search, om_double_scan, om_scan, refine_guess