int_ee_rel – ALPS
int_ee_rel Function
63 statements
public function int_ee_rel(om)
Uses
alps_var
This function returns the ee term in Eq. (2.9) for the relativistic calculation.
Arguments
Type Intent Optional Attributes Name
double complex, intent(in) :: om
Complex wave frequency .
Return Value doublecomplex
Calls
Called by
Contents
Call graph
int_ee_rel calls determine_sproc_rel
disp calls int_ee_rel
calc_eigen calls disp
map_search calls disp, refine_guess
om_double_scan calls disp, calc_eigen, secant
om_scan calls disp, calc_eigen, secant
refine_guess calls disp, secant
secant calls disp
alps calls map_search, om_double_scan, om_scan, refine_guess