int_T_res_rel – ALPS
int_T_res_rel Function
56 statements
private function int_T_res_rel(sproc_rel, nn, igamma, pparbar, mode)
Uses
alps_var
This function returns the T-tensor according to Eq. (2.10) of the code paper for the case in which it is evaluated at the complex resonance momentum for the relativistic calculation.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: sproc_rel
is_rel of the current process.
integer, intent(in) :: nn
Order of the Bessel function.
integer, intent(in) :: igamma
Index to loop over .
double complex, intent(in) :: pparbar
Relativistic parallel momentum.
integer, intent(in) :: mode
Index of the entries in the T-tensor of Eq. (2.10).
Return Value doublecomplex
Calls
Called by
Call graph
int_t_res_rel calls cbessj
cbessj calls fact
landau_integrate_rel calls int_t_res_rel
full_integrate calls landau_integrate_rel
disp calls full_integrate
calc_eigen calls disp
map_search calls disp, refine_guess
om_double_scan calls disp, calc_eigen, secant
om_scan calls disp, calc_eigen, secant
refine_guess calls disp, secant
secant calls disp
alps calls map_search, om_double_scan, om_scan, refine_guess