integrate_resU_rel – ALPS
integrate_resU_rel Function
117 statements
private function integrate_resU_rel(sproc_rel, om, nn, mode, igamma)
Uses
alps_var
alps_io
This function evaluates the integral with the integrand proportional to in Eq. (2.9) of the code paper for a relativistic calculation.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: sproc_rel
is_rel of the current process.
double complex, intent(in) :: om
Complex wave frequency .
integer, intent(in) :: nn
Order of the Bessel function.
integer, intent(in) :: mode
Index of the entries in the T-tensor of Eq. (2.10).
integer, intent(in) :: igamma
Index to loop over .
Return Value doublecomplex
Calls
Called by
Call graph
integrate_resu_rel calls alps_error, int_t_rel, principal_integral_rel, resu_rel
alps_error calls mpi_abort, output_time
int_t_rel calls bessj
principal_integral_rel calls funct_g_rel
bessj calls float, bessj0, bessj1
funct_g_rel calls int_t_rel
integrate_res_rel calls integrate_resu_rel
full_integrate calls integrate_res_rel
disp calls full_integrate
calc_eigen calls disp
map_search calls disp, refine_guess
om_double_scan calls disp, calc_eigen, secant, secant_osc
om_scan calls disp, calc_eigen, secant, secant_osc
refine_guess calls disp, secant, secant_osc
secant calls disp
secant_osc calls disp
alps calls map_search, om_double_scan, om_scan, refine_guess