integrate – ALPS
integrate Function
28 statements
private function integrate(om, nn, mode, iparmin, iparmax)
Uses
alps_var
This function performs the integral in Eq. (2.9) of the code paper, but without accounting for the Landau contour integral. It is called by full_integrate.
Arguments
Type Intent Optional Attributes Name
double complex, intent(in) :: om
Complex wave frequency .
integer, intent(in) :: nn
Order of the Bessel function.
integer, intent(in) :: mode
Index of the entries in the T-tensor of Eq. (2.10).
integer :: iparmin
Minimum limit index of parallel momentum for integration.
integer :: iparmax
Maximum limit index of parallel momentum for integration.
Return Value doublecomplex
Calls
Called by
Contents
Call graph
integrate calls int_t, resu
full_integrate calls integrate, integrate_res
integrate_res calls integrate
disp calls full_integrate
calc_eigen calls disp
map_search calls disp, refine_guess
om_double_scan calls disp, calc_eigen, secant
om_scan calls disp, calc_eigen, secant
refine_guess calls disp, secant
secant calls disp
alps calls map_search, om_double_scan, om_scan, refine_guess