isnancheck – ALPS
isnancheck Function
7 statements
public function isnancheck(input)
Checks if double precision number input is NaN.
Arguments
Type Intent Optional Attributes Name
double precision :: input
Variable to be checked.
Return Value logical
Called by
Contents
Call graph
om_double_scan calls isnancheck
om_scan calls isnancheck
output_fit calls isnancheck
determine_param_fit calls output_fit
alps calls om_double_scan, om_scan, determine_param_fit