landau_integrate_rel – ALPS
landau_integrate_rel Function
38 statements
public function landau_integrate_rel(om, nn, mode)
Uses
alps_analyt
alps_var
This function evaluates the Landau contour according to Eqs. (3.8) and (3.9) of the code paper for a relativistic calculation.
Arguments
Type Intent Optional Attributes Name
double complex, intent(in) :: om
Complex wave frequency .
integer, intent(in) :: nn
Order of the Bessel function.
integer, intent(in) :: mode
Index of the entries in the T-tensor of Eq. (2.10).
Return Value doublecomplex
Calls
Called by
Contents
Call graph
landau_integrate_rel calls determine_sproc_rel, eval_fit, int_t_res_rel
eval_fit calls distribution_analyt, fit_function
int_t_res_rel calls cbessj
cbessj calls fact
full_integrate calls landau_integrate_rel
disp calls full_integrate
calc_eigen calls disp
map_search calls disp, refine_guess
om_double_scan calls disp, calc_eigen, secant
om_scan calls disp, calc_eigen, secant
refine_guess calls disp, secant
secant calls disp
alps calls map_search, om_double_scan, om_scan, refine_guess