least_squares_fit – ALPS
least_squares_fit Subroutine
22 statements
public subroutine least_squares_fit(AA, BB, coeffs, npoly)
Uses
alps_var
Solves General Linear Least Squares Normal Equation
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: AA(0:npar,0:npoly)
Polynomial Basis
double precision, intent(in) :: BB(0:npar)
f0(is,iperp,:)
double precision, intent(out) :: coeffs(0:npoly)
fit coefficients
integer :: npoly
Order for polyhedral representation
Calls
Called by
Call graph
least_squares_fit calls dgemm, dgemv, dgesv
determine_glls calls least_squares_fit
determine_param_fit calls determine_glls
alps calls determine_param_fit