om_double_scan – ALPS
om_double_scan Subroutine
435 statements
public subroutine om_double_scan()
Uses
alps_var
alps_io
mpi
This subroutine scans along a prescribed plane in wavevector space to map out in this space. It is required that n_scan=2, and is invoked with option =2 KGK: This line causes the solution to (occasionally) smoothly transition to unphysical values. Suppressing until we understand the error.
KGK: This line causes the solution to (occasionally) smoothly transition to unphysical values. Suppressing until we understand the error.
Arguments
None
Calls
Called by
Call graph
om_double_scan calls mpi_barrier, mpi_bcast, alps_error, calc_eigen, determine_bessel_array, determine_nmax, disp, get_unused_unit, isnancheck, rtsec, secant, secant_osc, split_processes
alps_error calls mpi_abort, output_time
calc_eigen calls disp
determine_bessel_array calls bessj
determine_nmax calls mpi_barrier, bessj
disp calls mpi_barrier, mpi_bcast, mpi_reduce, calc_chi, determine_resonances, full_integrate, int_ee, int_ee_rel
secant calls mpi_barrier, disp
secant_osc calls mpi_barrier, disp
split_processes calls mpi_barrier
bessj calls float, bessj0, bessj1
calc_chi calls besseli, calc_chi_cold, calc_ypsilon
full_integrate calls integrate, integrate_res, integrate_res_rel, landau_integrate, landau_integrate_rel
int_ee_rel calls determine_sproc_rel
besseli calls bessi
calc_ypsilon calls besseli, dispfunct
integrate calls int_t, resu
integrate_res calls integrate, funct_g
integrate_res_rel calls determine_sproc_rel, integrate_resu_rel
landau_integrate calls eval_fit, int_t_res
landau_integrate_rel calls determine_sproc_rel, eval_fit, int_t_res_rel
bessi calls float, dfloat, bessi0, bessi1
dispfunct calls wofz
eval_fit calls distribution_analyt, fit_function, fit_function_poly
funct_g calls int_t
int_t_res_rel calls cbessj
integrate_resu_rel calls alps_error, int_t_rel, principal_integral_rel, resu_rel
cbessj calls fact
int_t_rel calls bessj
principal_integral_rel calls funct_g_rel
wofz calls dcos, dexp, dsin, idint, idnint
funct_g_rel calls int_t_rel
alps calls om_double_scan