output_time – ALPS
output_time Subroutine
9 statements
public subroutine output_time()
Outputs the date and time in a given format using intrinsic FORTRAN function.
Arguments
None
Called by
Call graph
alps_error calls output_time
alps calls output_time, alps_error, init_param, om_double_scan, om_scan, determine_param_fit, map_search, refine_guess
get_indexed_double_namelist_unit calls alps_error
get_indexed_namelist_unit calls alps_error
init_param calls alps_error, get_indexed_double_namelist_unit, get_indexed_namelist_unit
integrate_resu_rel calls alps_error
lm_nonlinear_fit calls alps_error
om_double_scan calls alps_error, disp, calc_eigen, secant, secant_osc
om_scan calls alps_error, disp, calc_eigen, secant, secant_osc
output_fit calls alps_error
set_polynomial_basis calls alps_error
determine_param_fit calls lm_nonlinear_fit, output_fit, set_polynomial_basis
integrate_res_rel calls integrate_resu_rel
full_integrate calls integrate_res_rel
disp calls full_integrate
calc_eigen calls disp
map_search calls disp, refine_guess
refine_guess calls disp, secant, secant_osc
secant calls disp
secant_osc calls disp