output_fit – ALPS
output_fit Subroutine
158 statements
private subroutine output_fit(qualitytotal)
Uses
alps_io
alps_var
This subroutine outputs the fit parameters for iperp=0 to stdout to monitor the fit.
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: qualitytotal
Quality of the total fit result.
Calls
Called by
Call graph
output_fit calls alps_error, eval_fit, isnancheck
alps_error calls mpi_abort, output_time
eval_fit calls distribution_analyt, fit_function, fit_function_poly
determine_param_fit calls output_fit
alps calls determine_param_fit