polyharmonic_spline – ALPS
polyharmonic_spline Subroutine
66 statements
public subroutine polyharmonic_spline(grid_coarse, gamma_coarse, pparbar_coarse, n_coarse, gamma_rel, pparbar, ngamma, npparbar, smoothing, f0_rel, is_rel, nspec_rel)
This soubroutine interpolates the grid with a polyharmonic thin-plate spline. This subroutine needs the LUPACK and BLAS libraries to evoke the dgesv subroutine. The method uses the Thin Plate Spline. We use these resources: http://cseweb.ucsd.edu/~sjb/eccv_tps.pdf http://www.univie.ac.at/nuhag-php/bibtex/open_files/po94_M%20J%20D%20Powell%2003%2093.pdf http://vision.ucsd.edu/sites/default/files/fulltext(4).pdf
Arguments
Type Intent Optional Attributes Name
double precision, intent(in) :: grid_coarse(n_coarse)
Coarse input grid for interpolation.
double precision, intent(in) :: gamma_coarse(n_coarse)
Coordinates of on coarse grid.
double precision, intent(in) :: pparbar_coarse(n_coarse)
Coordinates of relativistic parallel momentum on coarse grid.
integer, intent(in) :: n_coarse
Number of entries in coarse grid.
double precision, intent(in) :: gamma_rel(nspec_rel,0:ngamma,0:npparbar)
Coordinates of on fine grid.
double precision, intent(in) :: pparbar(nspec_rel,0:ngamma,0:npparbar)
Coordinates of relativistic parallel momentum on fine grid.
integer, intent(in) :: ngamma
Number of steps on fine output grid.
integer, intent(in) :: npparbar
Number of parallel momentum steps on fine output grid.
double precision, intent(in) :: smoothing
Smoothing parameter for spline interpolation.
double precision, intent(out) :: f0_rel(nspec_rel,0:ngamma,0:npparbar)
Fine output grid after interpolation.
integer :: is_rel
Index for relativistic species (if any).
integer :: nspec_rel
Number of relativistic species.
Calls
Called by
Contents
Call graph
polyharmonic_spline calls dgesv
derivative_f0_rel calls polyharmonic_spline
derivative_f0 calls derivative_f0_rel
alps calls derivative_f0