principal_integral_rel – ALPS
principal_integral_rel Function
59 statements
public function principal_integral_rel(sproc_rel, om, nn, mode, igamma, ipparbar_res, upperlimit)
Uses
alps_var
Arguments
Type Intent Optional Attributes Name
integer :: sproc_rel
double complex :: om
integer :: nn
integer :: mode
integer :: igamma
integer :: ipparbar_res
integer :: upperlimit
Return Value doublecomplex
Calls
Called by
Contents
Call graph
principal_integral_rel calls funct_g_rel
funct_g_rel calls int_t_rel
int_t_rel calls bessj
bessj calls float, bessj0, bessj1
integrate_resu_rel calls principal_integral_rel
integrate_res_rel calls integrate_resu_rel
full_integrate calls integrate_res_rel
disp calls full_integrate
calc_eigen calls disp
map_search calls disp, refine_guess
om_double_scan calls disp, secant
om_scan calls disp, calc_eigen, secant
refine_guess calls disp, secant
secant calls disp
alps calls map_search, om_double_scan, om_scan, refine_guess