read_in_params – ALPS
read_in_params Subroutine
27 statements
subroutine read_in_params()
This subroutine reads in system parameters input file (namelist) as argument after executable: ./interpolate input.in
Arguments
None
Calls
Called by
Namelists
Namelist system
Variables
Name Type Default Description
filename character(len=256) None
File name of input file for interpolation.
smoothing double precision None
Smoothing parameter for spline interpolation.
nperp integer None
Number of perpendicular steps on fine output grid.
npar integer None
Number of parallel steps on fine output grid.
ppar_min_set double precision None
Forced minimum perpendicular momentum for output.
ppar_max_set double precision None
Forced maximum parallel momentum for output.
pperp_min_set double precision None
Forced minimum perpendicular momentum for output.
pperp_max_set double precision None
Forced maximum perpendicular momentum for output.
mode integer None
Format of input grid (order pperp/ppar).
threshold double precision None
Lower treshold for f0-values (coarse grid) to be included.
out_to_file logical None
Check whether output should be written to file.
do_normalize logical None
Check whether normalisation should be applied.
mult_pperp double precision None
Scaling factor for perpendicular momentum.
mult_ppar double precision None
Scaling factor for parallel momentum.
mult_f double precision None
Scaling factor for f0.
Call graph
read_in_params calls get_runname, get_unused_unit
interpolate calls read_in_params