refine_guess – ALPS
refine_guess Subroutine
39 statements
public subroutine refine_guess()
Uses
alps_io
alps_var
mpi
This subroutine refines the guess at the starting point of the search for solutions to the dispersion relation when scanning. It is also used by map_search to identify the roots on the map.
Arguments
None
Calls
Called by
Call graph
refine_guess calls mpi_barrier, disp, get_unused_unit, rtsec, secant, secant_osc
disp calls mpi_barrier, mpi_bcast, mpi_reduce, calc_chi, determine_resonances, full_integrate, int_ee, int_ee_rel
secant calls mpi_barrier, disp
secant_osc calls mpi_barrier, disp
calc_chi calls besseli, calc_chi_cold, calc_ypsilon
full_integrate calls integrate, integrate_res, integrate_res_rel, landau_integrate, landau_integrate_rel
int_ee_rel calls determine_sproc_rel
besseli calls bessi
calc_ypsilon calls besseli, dispfunct
integrate calls int_t, resu
integrate_res calls integrate, funct_g
integrate_res_rel calls determine_sproc_rel, integrate_resu_rel
landau_integrate calls eval_fit, int_t_res
landau_integrate_rel calls determine_sproc_rel, eval_fit, int_t_res_rel
bessi calls dfloat, float, bessi0, bessi1
dispfunct calls wofz
eval_fit calls distribution_analyt, fit_function, fit_function_poly
funct_g calls int_t
int_t_res_rel calls cbessj
integrate_resu_rel calls alps_error, int_t_rel, principal_integral_rel, resu_rel
alps_error calls mpi_abort, output_time
cbessj calls fact
int_t_rel calls bessj
principal_integral_rel calls funct_g_rel
wofz calls dcos, dexp, dsin, idint, idnint
bessj calls float, bessj0, bessj1
funct_g_rel calls int_t_rel
map_search calls refine_guess
alps calls refine_guess, map_search