rtsec – ALPS
rtsec Function
54 statements
public function rtsec(func, xin, in, iflag)
Uses
alps_var
An alternative implementation of the secant method, adapted from PLUME.
Arguments
Type Intent Optional Attributes Name
double complex :: func
Function whose roots are to be identified. For ALPS, this is the dispersion relation.
double complex :: xin
Initial Guess for complex frequency.
integer, intent(in) :: in
Root number
integer :: iflag
Flag for number of steps taken.
Return Value doublecomplex
Called by
Call graph
om_double_scan calls rtsec
om_scan calls rtsec
refine_guess calls rtsec
map_search calls refine_guess
alps calls om_double_scan, om_scan, refine_guess, map_search