set_polynomial_basis – ALPS
set_polynomial_basis Subroutine
24 statements
private subroutine set_polynomial_basis(is)
Uses
alps_io
alps_var
This subroutine evaluates the General Linear Least Squares fit to the distribution function for component 'is' using the selected polynomial basis functions.
Arguments
Type Intent Optional Attributes Name
integer :: is
Index of species.
Calls
Called by
Call graph
set_polynomial_basis calls alps_error
alps_error calls mpi_abort, output_time
determine_param_fit calls set_polynomial_basis
alps calls determine_param_fit