split_processes – ALPS
split_processes Subroutine
70 statements
public subroutine split_processes()
Uses
alps_var
mpi
This subroutine defines the tasks for the individual processes. It uses the number of species and the required orders of the Bessel functions to define the splitting across the MPI processes.
Arguments
None
Calls
Called by
Call graph
split_processes calls mpi_barrier
om_double_scan calls split_processes
om_scan calls split_processes
alps calls split_processes, om_double_scan, om_scan