WOFZ – ALPS
WOFZ Subroutine
98 statements
private subroutine WOFZ(XI, YI, U, V, FLAG)
Given a complex number Z = (XI,YI), this subroutine computes the value of the Faddeeva function W(Z) = exp(-Z2)erfc(-IZ), where erfc is the complex complementary error function and I is the imaginary unit.
Arguments
Type Intent Optional Attributes Name
real :: XI
real :: YI
real :: U
real :: V
logical :: FLAG
Calls
Called by
Call graph
wofz calls dcos, dexp, dsin, idint, idnint
dispfunct calls wofz
calc_ypsilon calls dispfunct
calc_chi calls calc_ypsilon
disp calls calc_chi
calc_eigen calls disp
map_search calls disp, refine_guess
om_double_scan calls disp, calc_eigen, secant, secant_osc
om_scan calls disp, calc_eigen, secant, secant_osc
refine_guess calls disp, secant, secant_osc
secant calls disp
secant_osc calls disp
alps calls map_search, om_double_scan, om_scan, refine_guess