alps – ALPS
alps Program
79 statements
Uses
alps_io
alps_fns
alps_var
mpi
alps_analyt
alps_com
Calls
Variables
Type Attributes Name Initial
integer :: ik
Index for iterating through wavevector scans with om_scan or om_double_scan
Call graph
alps calls mpi_barrier, mpi_comm_rank, mpi_comm_size, mpi_finalize, mpi_init, alps_error, alps_error_init, derivative_f0, determine_bessel_array, determine_nmax, determine_param_fit, display_credits, init_param, map_search, om_double_scan, om_scan, output_time, pass_distribution, pass_instructions, read_f0, refine_guess, split_processes
alps_error calls output_time, mpi_abort
alps_error_init calls get_runname, get_unused_unit
derivative_f0 calls derivative_f0_rel, get_unused_unit
determine_bessel_array calls bessj
determine_nmax calls mpi_barrier, bessj
determine_param_fit calls determine_glls, lm_nonlinear_fit, output_fit, set_polynomial_basis
init_param calls alps_error, bm_read, fit_read, get_indexed_double_namelist_unit, get_indexed_namelist_unit, get_unused_unit, map_read, poly_read, scan_read, solution_read, spec_read
map_search calls refine_guess, mpi_bcast, disp, find_minima, get_unused_unit
om_double_scan calls mpi_barrier, alps_error, determine_bessel_array, determine_nmax, split_processes, mpi_bcast, calc_eigen, disp, get_unused_unit, isnancheck, rtsec, secant, secant_osc
om_scan calls mpi_barrier, alps_error, determine_bessel_array, determine_nmax, split_processes, mpi_bcast, calc_eigen, disp, get_unused_unit, isnancheck, rtsec, secant, secant_osc
pass_distribution calls mpi_bcast
pass_instructions calls mpi_bcast
read_f0 calls get_unused_unit
refine_guess calls mpi_barrier, disp, get_unused_unit, rtsec, secant, secant_osc
split_processes calls mpi_barrier
bessj calls float, bessj0, bessj1
calc_eigen calls disp
derivative_f0_rel calls get_unused_unit, polyharmonic_spline
determine_glls calls least_squares_fit
disp calls mpi_barrier, mpi_bcast, mpi_reduce, calc_chi, determine_resonances, full_integrate, int_ee, int_ee_rel
get_indexed_double_namelist_unit calls alps_error, get_unused_unit, input_unit, input_unit_exist
get_indexed_namelist_unit calls alps_error, get_unused_unit, input_unit, input_unit_exist
lm_nonlinear_fit calls alps_error, dgetrf, dgetri, determine_jt, fit_function
output_fit calls alps_error, isnancheck, eval_fit
secant calls mpi_barrier, disp
secant_osc calls mpi_barrier, disp
set_polynomial_basis calls alps_error
calc_chi calls besseli, calc_chi_cold, calc_ypsilon
eval_fit calls fit_function, distribution_analyt, fit_function_poly
full_integrate calls integrate, integrate_res, integrate_res_rel, landau_integrate, landau_integrate_rel
int_ee_rel calls determine_sproc_rel
least_squares_fit calls dgemm, dgemv, dgesv
polyharmonic_spline calls dgesv
besseli calls bessi
calc_ypsilon calls besseli, dispfunct
integrate calls int_t, resu
integrate_res calls integrate, funct_g
integrate_res_rel calls determine_sproc_rel, integrate_resu_rel
landau_integrate calls eval_fit, int_t_res
landau_integrate_rel calls eval_fit, determine_sproc_rel, int_t_res_rel
bessi calls float, dfloat, bessi0, bessi1
dispfunct calls wofz
funct_g calls int_t
int_t_res_rel calls cbessj
integrate_resu_rel calls alps_error, int_t_rel, principal_integral_rel, resu_rel
cbessj calls fact
int_t_rel calls bessj
principal_integral_rel calls funct_g_rel
wofz calls dcos, dexp, dsin, idint, idnint
funct_g_rel calls int_t_rel