generate_distribution – ALPS
generate_distribution Program
393 statements
Uses
alps_distribution_analyt
This program generates distribution files for input into ALPS based on pre-defined functions.
Calls
Contents
Variables
iperp ipar nperp npar nspec is unit_out writeName outputName dpperp dppar ppar_max pperp_max iperpcorr ifit_1 ifit_2 ifit_3 ifit_4 ifit_5 ppar pperp f0 ms tau alph p_drift kappa maxPperp maxPpar autoscale distribution beta vA maxP pi integrate norm a BESSK ppar_C unit stdout_unit input_unit_no error_unit_no runname
Functions
input_unit_exist input_unit
Subroutines
read_in_params spec_read get_indexed_namelist_unit get_unused_unit get_runname
Variables
Type Attributes Name Initial
integer :: iperp
Index to loop over perpendicular momentum.
integer :: ipar
Index to loop over parallel momentum.
integer :: nperp
Number of steps in perpendicular momentum.
integer :: npar
Number of steps in parallel momentum.
integer :: nspec
Total number of plasma species.
integer :: is
Index to loop over plasma species.
integer, dimension(:), allocatable :: unit_out
Index for unit for output. (1:nspec)
character(len=500) :: writeName
String for part of file name.
character(len=500) :: outputName
String for part of file name.
double precision :: dpperp
Inifinitesimal step in perpendicular momentum.
double precision :: dppar
Inifinitesimal step in parallel momentum.
double precision :: ppar_max
Maximum parallel momentum.
double precision :: pperp_max
Maximum perpendicular momentum.
double precision :: iperpcorr
Perpendicular correction .
double precision :: ifit_1
Ideal first fit parameter .
double precision :: ifit_2
Ideal second fit parameter .
double precision :: ifit_3
Ideal third fit parameter .
double precision :: ifit_4
Ideal fourth fit parameter .
double precision :: ifit_5
Ideal fifth fit parameter .
double precision :: ppar
Parallel momentum.
double precision :: pperp
Perpendicular momentum.
double precision :: f0
Distribution function.
double precision, dimension(:), allocatable :: ms
Mass of species. (1:nspec)
double precision, dimension(:), allocatable :: tau
Parallel temperature ratio of species. (1:nspec)
double precision, dimension(:), allocatable :: alph
Temperature anisotropy of species. (1:nspec)
double precision, dimension(:), allocatable :: p_drift
Drift momentum of species. (1:nspec)
double precision, dimension(:), allocatable :: kappa
Kappa index of species. (1:nspec)
double precision, dimension(:), allocatable :: maxPperp
Maximum perpendicular momentum of species. (1:nspec)
double precision, dimension(:), allocatable :: maxPpar
Maximum parallel momentum of species. (1:nspec)
logical, dimension (:), allocatable :: autoscale
Flag for autoscaling of grid for species. (1:nspec)
integer, dimension(:), allocatable :: distribution
Type of distribution for species. (1:nspec)
double precision :: beta
Plasma beta.
double precision :: vA
Ratio of Alfven speed to c.
double precision :: maxP
Maximum momentum.
double precision :: pi
Pi.
double precision :: integrate
Integration variable.
double precision :: norm
Normalisation factor for f0.
double precision :: a
Helper variable for parts of distributions.
double precision :: BESSK
Modified Bessel function.
double complex :: ppar_C
Complex version of parallel momentum.
integer :: unit
Unit for file i/o.
integer, parameter :: stdout_unit = 6
Flag for file i/o.
integer, save :: input_unit_no
Saved input unit for use with multiple read in calls.
integer, save :: error_unit_no = stdout_unit
Error output unit.
character(len=500) :: runname
String parameter for input file.
Functions
function input_unit_exist(nml, exist)
Determine if a particular namelist already opened.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: nml
Namelist to be opened.
logical, intent(out) :: exist
Determination if namelist is open.
Return Value integer
I/O dummy index.
function input_unit(nml)
Assigns input unit for namelist opening.
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: nml
Namelist string.
Return Value integer
I/O dummy index.
Subroutines
subroutine read_in_params()
This subroutine reads in the parameters for the generation of distribution functions for ALPS.
Arguments
None
subroutine spec_read(is)
Subroutine for reading in species parameters.
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: is
Species index.
subroutine get_indexed_namelist_unit(unit, nml, index_in)
Determines unused I/O unit.
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: unit
Unit to be defined.
character(len=*), intent(in) :: nml
Character string for namelist to be read in.
integer, intent(in) :: index_in
Index of namelist to be read in.
subroutine get_unused_unit(unit)
Determine unused number for I/O index.
Arguments
Type Intent Optional Attributes Name
integer, intent(out) :: unit
Unit to be assigned.
subroutine get_runname(runname)
Get runname for output files from input argument.
Arguments
Type Intent Optional Attributes Name
character(len=500), intent(out) :: runname
Basename for file I/O.
Call graph
generate_distribution calls distribution_analyt, read_in_params
read_in_params calls get_indexed_namelist_unit, get_runname, get_unused_unit, spec_read
get_indexed_namelist_unit calls get_unused_unit, input_unit_exist, input_unit